### ISSUE TITLE
Dataset release

### ISSUE THREAD

**Issue by niejiahao1998** [wjpoom/SPEC#2]
When will you release the whole dataset? We are considering using your data to research a new topic.

**Comment by wjpoom** [comment]
Thank you for your attention, actually we are working on open source data and code and plan to release it this month

**Comment by niejiahao1998** [comment]
Thank you very much.

**Comment by buptlyf** [comment]
When will you release the whole dataset?

**Comment by wjpoom** [comment]
Hi, we are pleased to inform you that the data and code for SPEC have been here, feel free to have a try. Sorry for the delay~
